### ISSUE TITLE
What is the best way to install 'red_string_grouper' for anaconda environment?

### ISSUE THREAD

**Issue by iibarant** [ParticularMiner/red_string_grouper#1]
Hi @ParticularMiner,

It is a great addition, but unfortunately, unlike string_grouper,
 
``` python
 pip install red_string_grouper     
```
does not work.

**Comment by ParticularMiner** [comment]
@iibarant 

I’m not sure why.  It works for me though.  What is your installation log like?

**Comment by iibarant** [comment]
There you go ...

![image](https://user-images.githubusercontent.com/89100191/133634517-0cf454d6-bfd3-475e-a563-13fe83f6d1f1.png)

**Comment by ParticularMiner** [comment]
Thanks @iibarant 

Could you also please try

    pip -v install red_string_grouper

to give a more verbose output.

**Comment by ParticularMiner** [comment]
@iibarant 

you could also first try upgrading pip:

     pip install --upgrade pip

and see if the error goes away after that.

**Comment by iibarant** [comment]
pip -v install red_string_grouper
Using pip 20.2.4 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-ephem-wheel-cache-uqrec0bw
Created temporary directory: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3
Initialized build tracking at /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3
Created build tracker: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3
Entered build tracker: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3
Created temporary directory: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-install-j2e0vb2w
1 location(s) to search for versions of red-string-grouper:
* https://pypi.org/simple/red-string-grouper/
Fetching project page and analyzing links: https://pypi.org/simple/red-string-grouper/
Getting page https://pypi.org/simple/red-string-grouper/
Found index url https://pypi.org/simple
Getting credentials from keyring for https://pypi.org/simple
Getting credentials from keyring for pypi.org
Looking up "https://pypi.org/simple/red-string-grouper/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/red-string-grouper/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/ce/76/280dca9b9cccbba0e43796648de8365f7c31689ca408eb72d8b45d4dbee3/red_string_grouper-0.0.0.tar.gz#sha256=064287af26423187fa02d9ffaddaf8a9a3d815f1fe5c05c6d09ab297c30c119b (from https://pypi.org/simple/red-string-grouper/), version: 0.0.0
  Found link https://files.pythonhosted.org/packages/88/4a/c2cc312020089570df1b08fa5e42cab0598d01d7a28678ccf605f639fd90/red_string_grouper-0.0.1.tar.gz#sha256=4a90d3ec38657bb0ef033efa4a893df530ba52238fb7023a2126528859dabb3f (from https://pypi.org/simple/red-string-grouper/), version: 0.0.1
Given no hashes to check 2 links for project 'red-string-grouper': discarding no candidates
Using version 0.0.1 (newest of versions: 0.0.0, 0.0.1)
Collecting red_string_grouper
  Created temporary directory: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-unpack-1zxgyk52
  Getting credentials from keyring for files.pythonhosted.org
  Looking up "https://files.pythonhosted.org/packages/88/4a/c2cc312020089570df1b08fa5e42cab0598d01d7a28678ccf605f639fd90/red_string_grouper-0.0.1.tar.gz" in the cache
  Current age based on date: 2997
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 2997
  Using cached red_string_grouper-0.0.1.tar.gz (34 kB)
  Added red_string_grouper from https://files.pythonhosted.org/packages/88/4a/c2cc312020089570df1b08fa5e42cab0598d01d7a28678ccf605f639fd90/red_string_grouper-0.0.1.tar.gz#sha256=4a90d3ec38657bb0ef033efa4a893df530ba52238fb7023a2126528859dabb3f to build tracker '/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3'
    Running setup.py (path:/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-install-j2e0vb2w/red-string-grouper/setup.py) egg_info for package red-string-grouper
    Created temporary directory: /private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-pip-egg-info-trbwsd5n
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-install-j2e0vb2w/red-string-grouper/setup.py", line 33, in <module>
        long_description = f.read()
      File "/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 443: invalid start byte
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed red_string_grouper from https://files.pythonhosted.org/packages/88/4a/c2cc312020089570df1b08fa5e42cab0598d01d7a28678ccf605f639fd90/red_string_grouper-0.0.1.tar.gz#sha256=4a90d3ec38657bb0ef033efa4a893df530ba52238fb7023a2126528859dabb3f from build tracker '/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3'
Removed build tracker: '/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-req-tracker-a8_276b3'

**Comment by iibarant** [comment]
@ParticularMiner,
 
pip update did not solve the issue.

Log after the update:

pip -v install red_string_grouper
Using pip 21.2.4 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Collecting red_string_grouper
  Using cached red_string_grouper-0.0.1.tar.gz (34 kB)
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-install-k5mctf4w/red-string-grouper_17d0d61f773a4ed88d87055c0666a9ae/setup.py", line 33, in <module>
        long_description = f.read()
      File "/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 443: invalid start byte
WARNING: Discarding https://files.pythonhosted.org/packages/88/4a/c2cc312020089570df1b08fa5e42cab0598d01d7a28678ccf605f639fd90/red_string_grouper-0.0.1.tar.gz#sha256=4a90d3ec38657bb0ef033efa4a893df530ba52238fb7023a2126528859dabb3f (from https://pypi.org/simple/red-string-grouper/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached red_string_grouper-0.0.0.tar.gz (34 kB)
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h_/8zmv8njn1yz3vpdc8ycrtdlm0000gp/T/pip-install-k5mctf4w/red-string-grouper_b7f7a66a2ad34909998637e9649d7802/setup.py", line 33, in <module>
        long_description = f.read()
      File "/opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 443: invalid start byte
WARNING: Discarding https://files.pythonhosted.org/packages/ce/76/280dca9b9cccbba0e43796648de8365f7c31689ca408eb72d8b45d4dbee3/red_string_grouper-0.0.0.tar.gz#sha256=064287af26423187fa02d9ffaddaf8a9a3d815f1fe5c05c6d09ab297c30c119b (from https://pypi.org/simple/red-string-grouper/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement red_string_grouper (from versions: 0.0.0, 0.0.1)
ERROR: No matching distribution found for red_string_grouper

**Comment by ParticularMiner** [comment]
Thanks @iibarant 

I have confirmed using [action workflows](https://github.com/ParticularMiner/red_string_grouper/actions) that indeed Windows is able to install  red_string_grouper successfully but not ubuntu (and therefore not Mac).  I'm looking into the issue.  Will get back to you.

**Comment by ParticularMiner** [comment]
@iibarant

I hope it works now.  At least it works for ubuntu and Windows.  The solution was to change the text-file encoding of README.md to UTF-8.

Without your notice I would not have even realized that such a problem could exist.  You are very helpful.  Thanks.

**Comment by iibarant** [comment]
@ParticularMiner 
I was able to install it after I installed Xcode package on Mac.
Thank you

**Comment by ParticularMiner** [comment]
@iibarant 

I can now confirm that installation on macOS is now possible:  [see test results](https://github.com/ParticularMiner/red_string_grouper/runs/3628296010?check_suite_focus=true).
